import streamlit as st

from rag_assistant.config import load_config
from rag_assistant.services import asset_service
from rag_assistant.services import notes_service
from rag_assistant.services.notes_pdf_service import render_notes_markdown_to_pdf
from rag_assistant.ui import render_sidebar, session_state

st.set_page_config(page_title="Notes", layout="wide")

subject_id = render_sidebar() or session_state.get_selected_subject()
st.title("Notes")

if not subject_id:
    st.warning("Please create and select a subject on Home.")
    st.stop()

assets = asset_service.list_assets(subject_id)
if not assets:
    st.info("No assets uploaded yet. Add files on the Upload page first.")
    st.stop()

asset_options = {f"{a['original_filename']} ({a['asset_id']})": a for a in assets}
selected_label = st.selectbox("Choose asset", list(asset_options.keys()))
selected_asset = asset_options[selected_label]
asset_id = selected_asset["asset_id"]
asset_filename = selected_asset.get("original_filename", asset_id)

edit_key = f"notes_edit_mode_{asset_id}"
content_key = f"notes_content_{asset_id}"
if edit_key not in st.session_state:
    st.session_state[edit_key] = False
preview_key = f"notes_preview_{asset_id}"

latest = notes_service.get_latest_notes(subject_id, asset_id)
if content_key not in st.session_state:
    st.session_state[content_key] = latest.get("markdown", "") if latest else ""
if preview_key not in st.session_state:
    st.session_state[preview_key] = latest.get("markdown", "") if latest else ""

regenerate = st.checkbox("Regenerate notes (LLM)", value=False, help="Generate a fresh set of notes from slides.")
debug_key = f"notes_debug_{asset_id}"
debug_enabled = st.checkbox("Debug notes logging", value=st.session_state.get(debug_key, False))
st.session_state[debug_key] = debug_enabled
log_key = f"notes_debug_log_{asset_id}"
if log_key not in st.session_state:
    st.session_state[log_key] = []
if st.button("Clear debug log"):
    st.session_state[log_key] = []
notes_web_key = f"notes_web_aug_{asset_id}"
allow_notes_web = st.checkbox(
    "Allow web augmentation for notes", value=st.session_state.get(notes_web_key, True)
)
st.session_state[notes_web_key] = allow_notes_web
mode_key = f"notes_web_mode_{asset_id}"
notes_web_mode = st.selectbox("Notes web mode", ["auto", "always", "never"], index=0)
max_queries = st.number_input("Max web queries per note", min_value=1, max_value=5, value=2, step=1)
max_results = st.number_input("Max web results per query", min_value=1, max_value=10, value=5, step=1)
allow_domains = st.text_area("Allow domains (one per line)", value="")
block_domains = st.text_area("Block domains (one per line)", value="")
col1, col2, col3 = st.columns(3)
with col1:
    if st.button("Generate Notes", disabled=bool(latest) and not regenerate):
        with st.spinner("Generating notes..."):
            try:
                cfg = load_config()
                cfg.notes.debug = debug_enabled
                cfg.notes.web_augmentation_enabled = allow_notes_web
                cfg.notes.web_mode = notes_web_mode
                cfg.notes.max_web_queries_per_notes = int(max_queries)
                cfg.notes.max_web_results_per_query = int(max_results)
                cfg.notes.web_allow_domains = [d.strip() for d in allow_domains.splitlines() if d.strip()]
                cfg.notes.web_block_domains = [d.strip() for d in block_domains.splitlines() if d.strip()]
                if debug_enabled:
                    cfg._notes_trace = st.session_state[log_key]
                res = notes_service.generate_notes_for_asset(subject_id, asset_id, config=cfg, trace=st.session_state[log_key] if debug_enabled else None)
                latest = notes_service.get_latest_notes(subject_id, asset_id, cfg)
                st.session_state[content_key] = latest.get("markdown", "")
                st.success(f"Notes ready (version {res.get('version')})")
            except Exception as exc:
                st.error(f"Failed to generate notes: {exc}")

with col2:
    if st.button("Edit", disabled=not latest):
        st.session_state[edit_key] = True
        st.session_state[preview_key] = st.session_state.get(content_key, latest.get("markdown", ""))


if latest:
    st.caption(
        f"Version {latest.get('version')} • Generated by {latest.get('generated_by')} • Notes ID: {latest.get('notes_id')}"
    )
    current_markdown = st.session_state.get(content_key, latest.get("markdown", ""))
    with col3:
        try:
            st.download_button(
                "Download PDF",
                data=render_notes_markdown_to_pdf(current_markdown, title=asset_filename),
                file_name=f"{asset_filename}_notes.pdf",
                mime="application/pdf",
                disabled=not bool(current_markdown),
            )
        except Exception as exc:
            st.error(f"Failed to render PDF: {exc}")

    if st.session_state[edit_key]:
        st.subheader("Edit notes")
        top_c1, top_c2, top_c3, top_c4 = st.columns([3, 1, 1, 1])
        with top_c1:
            st.caption(asset_filename)
        with top_c2:
            save_clicked = st.button("Save", type="primary")
        with top_c3:
            rerender_clicked = st.button("Re-render preview")
        with top_c4:
            cancel_clicked = st.button("Cancel")

        col_edit, col_preview = st.columns(2)
        with col_edit:
            content = st.text_area(
                "Markdown",
                value=st.session_state.get(content_key, latest.get("markdown", "")),
                height=800,
                key=f"notes_editor_{asset_id}",
            )
            st.session_state[content_key] = content
        with col_preview:
            st.markdown(st.session_state.get(preview_key, content))

        if rerender_clicked:
            st.session_state[preview_key] = st.session_state.get(content_key, content)

        if cancel_clicked:
            st.session_state[edit_key] = False
            st.session_state[content_key] = latest.get("markdown", "")
            st.session_state[preview_key] = latest.get("markdown", "")
            st.rerun()

        if save_clicked:
            with st.spinner("Saving and re-indexing..."):
                try:
                    cfg = load_config()
                    cfg.notes.debug = debug_enabled
                    if debug_enabled:
                        cfg._notes_trace = st.session_state[log_key]
                    res = notes_service.update_notes(latest["notes_id"], content, edited_by="user", config=cfg)
                    st.session_state[edit_key] = False
                    st.session_state[content_key] = content
                    st.session_state[preview_key] = content
                    st.success(f"Saved version {res.get('version')}")
                    st.rerun()
                except Exception as exc:
                    st.error(f"Failed to save notes: {exc}")
    else:
        st.subheader("Latest notes")
        st.markdown(latest.get("markdown", ""))
else:
    st.info("No notes for this asset yet. Click 'Generate Notes' to create them.")

with st.expander("Show debug log"):
    st.caption("Notes debug trace (session-scoped).")
    if st.session_state[log_key]:
        st.code("\n".join(st.session_state[log_key]), language="text")
    else:
        st.text("No debug entries yet.")
