import textwrap
from io import BytesIO

import streamlit as st
from PIL import Image, ImageDraw, ImageFont

from rag_assistant.services import asset_service
from rag_assistant.services import notes_service
from rag_assistant.ui import render_sidebar, session_state

st.set_page_config(page_title="Notes", layout="wide")

subject_id = render_sidebar() or session_state.get_selected_subject()
st.title("Notes")

if not subject_id:
    st.warning("Please create and select a subject on Home.")
    st.stop()

assets = asset_service.list_assets(subject_id)
if not assets:
    st.info("No assets uploaded yet. Add files on the Upload page first.")
    st.stop()

asset_options = {f"{a['original_filename']} ({a['asset_id']})": a for a in assets}
selected_label = st.selectbox("Choose asset", list(asset_options.keys()))
selected_asset = asset_options[selected_label]
asset_id = selected_asset["asset_id"]
asset_filename = selected_asset.get("original_filename", asset_id)

edit_key = f"notes_edit_mode_{asset_id}"
content_key = f"notes_content_{asset_id}"
if edit_key not in st.session_state:
    st.session_state[edit_key] = False

latest = notes_service.get_latest_notes(subject_id, asset_id)
if latest and content_key not in st.session_state:
    st.session_state[content_key] = latest.get("markdown", "")

regenerate = st.checkbox("Regenerate notes (LLM)", value=False, help="Generate a fresh set of notes from slides.")
col1, col2, col3 = st.columns(3)
with col1:
    if st.button("Generate Notes", disabled=bool(latest) and not regenerate):
        with st.spinner("Generating notes..."):
            try:
                res = notes_service.generate_notes_for_asset(subject_id, asset_id)
                latest = notes_service.get_latest_notes(subject_id, asset_id)
                st.session_state[content_key] = latest.get("markdown", "")
                st.success(f"Notes ready (version {res.get('version')})")
            except Exception as exc:
                st.error(f"Failed to generate notes: {exc}")

with col2:
    if st.button("Edit", disabled=not latest):
        st.session_state[edit_key] = True


def _markdown_to_pdf_bytes(markdown: str, title: str) -> bytes:
    """Render simple Markdown-like text to a single-page PDF using Pillow."""
    lines = []
    for raw_line in markdown.splitlines():
        if raw_line.strip().startswith("#"):
            text = raw_line.lstrip("#").strip()
            lines.append(text.upper())
        elif raw_line.strip().startswith(("-", "*")):
            lines.append(f"• {raw_line.lstrip('-* ').strip()}")
        else:
            lines.append(raw_line)
    font = ImageFont.load_default()
    wrapped: list[str] = []
    for line in lines or [""]:
        wrapped.extend(textwrap.wrap(line, width=90) or [" "])
    line_height = font.getbbox("Ag")[3]
    padding = 20
    height = max(120, (line_height + 4) * (len(wrapped) + 2) + padding * 2)
    width = 800
    img = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(img)
    y = padding
    draw.text((padding, y), f"Notes: {title}", fill="black", font=font)
    y += line_height + 12
    for line in wrapped:
        draw.text((padding, y), line, fill="black", font=font)
        y += line_height + 4
    buf = BytesIO()
    img.save(buf, format="PDF")
    buf.seek(0)
    return buf.getvalue()

if latest:
    st.caption(
        f"Version {latest.get('version')} • Generated by {latest.get('generated_by')} • Notes ID: {latest.get('notes_id')}"
    )
    current_markdown = st.session_state.get(content_key, latest.get("markdown", ""))
    pdf_bytes = _markdown_to_pdf_bytes(current_markdown, asset_filename) if current_markdown else b""
    with col3:
        st.download_button(
            "Download PDF",
            data=pdf_bytes,
            file_name=f"{asset_filename}_notes.pdf",
            mime="application/pdf",
            disabled=not bool(pdf_bytes),
        )

    if st.session_state[edit_key]:
        st.subheader("Edit notes")
        content = st.text_area(
            "Markdown",
            value=st.session_state.get(content_key, latest.get("markdown", "")),
            height=380,
            key=f"notes_editor_{asset_id}",
        )
        if st.button("Save", type="primary"):
            with st.spinner("Saving and re-indexing..."):
                try:
                    res = notes_service.update_notes(latest["notes_id"], content, edited_by="user")
                    st.session_state[edit_key] = False
                    st.session_state[content_key] = content
                    latest = notes_service.get_latest_notes(subject_id, asset_id)
                    st.success(f"Saved version {res.get('version')}")
                except Exception as exc:
                    st.error(f"Failed to save notes: {exc}")
        st.button("Cancel", on_click=lambda: st.session_state.update({edit_key: False, content_key: latest.get("markdown", "")}))
    else:
        st.subheader("Latest notes")
        st.markdown(latest.get("markdown", ""))
else:
    st.info("No notes for this asset yet. Click 'Generate Notes' to create them.")
